sudo: required

services:
    - docker
    
#before_install:
#    - docker build -t nitinrai17/expensetrackerui-test -f ./expensetrackerui/Dockerfile.dev ./expensetrackerui
#    - docker build -t nitinrai17/expensetrackerapi-test -f ./expensetrackerapi/Dockerfile.dev ./expensetrackerapi
script:
#    - docker run -e CI=true nitinrai17/fibcalculator_client-test npm run test -- --coverage
     -  docker --version    

after_success: 
    - docker build -t nitinrai17/expensetrackerui -f ./expensetrackerui/Dockerfile ./expensetrackerui
    - docker build -t nitinrai17/expensetrackerapi -f ./expensetrackerapi/Dockerfile.dev ./expensetrackerapi
    - docker build -t nitinrai17/userapi -f ./userapi/Dockerfile ./userapi
    
    # login into docker hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #  take those image and push into the docker hub 
    - docker push  nitinrai17/expensetrackerui 
    - docker push  nitinrai17/expensetrackerapi
    - docker push  nitinrai17/userapi

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: ExpenseTracker
    env: ExpenseTracker-env-1
    bucket_name: expensetrackerapp
    bucket_path: ExpenseTracker
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
