version: '3'
services:
    #API          
    expensetrackerapi:
        build: 
            dockerfile: Dockerfile.dev
            context: ./expensetrackerapi
        expose:
            - 8080
        ports:
            - '8080:8080'

    #user
    userapi:
        build: 
            dockerfile: Dockerfile
            context: ./userapi
        expose:
            - 8100
        ports:
            - '8100:8100'

    #UI        
    expensetrackerui:
        build:
            context: ./expensetrackerui
            dockerfile: Dockerfile
            args:
                REACT_APP_API_BASE_URL: http://expensetrackerapi:8080/api/1.0
        expose:
            - 80        
        ports:
            - '80:80'
        environment: 
            - REACT_APP_API_BASE_URL=http://expensetrackerapi:8080/api/1.0
        restart: always
        depends_on:
                - expensetrackerapi